wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.1
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.43.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1737897429
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 105
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 105
      3:
      - 17
      - 23
      - 37
      4: 3.11.1
      5: 0.17.5
      6: 4.43.4
      8:
      - 4
      - 5
      13: darwin-arm64
